# Generated by Django 2.2.6 on 2019-10-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_press', models.CharField(max_length=255)),
                ('book_category', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_date', models.CharField(max_length=255)),
                ('movie_star', models.CharField(max_length=255)),
                ('movie_category', models.CharField(max_length=255)),
                ('movie_score', models.DecimalField(decimal_places=0.1, max_digits=1)),
            ],
        ),
    ]
