# Generated by Django 2.2.6 on 2019-11-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
